#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: rest
---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gummyfish-service
  namespace: rest
  labels:
    app: gummyfish-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gummyfish-service
  template:
    metadata:
      labels:
        app: gummyfish-service
    spec:
      containers:
      - name: gummyfish-service
        image: bossmojoman/gummyfishservice:${TAG}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources: 
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: gummyfish-service
  namespace: rest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: gummyfish-service
  type: ClusterIP
---